# Generated by Django 3.0.6 on 2020-07-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FND', 'Fundacja'), ('NGO', 'Organizacja pozarządowa'), ('LOC', 'Zbiórka lokalna')], default='FND', max_length=3)),
                ('category', models.ManyToManyField(to='charity.Category')),
            ],
        ),
    ]
